In [3]:
import pandas as pd
import numpy as np
import json
from pathlib import Path

In [4]:
creds_path = Path("creds") / "gdrive_folder.json"
with creds_path.open() as f:
    sb_data_path = json.load(f)

sb_data_folder_path = sb_data_path["statsbomb_data_folder_path"]

In [6]:
df_matches = pd.read_parquet(sb_data_folder_path + "/USLChampionship_2025_matches.parquet")

In [7]:
df_matches.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,attendance,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3985715,2025-07-16,23:30:00.000,USA - USL Championship,2025,Hartford Athletic,Tampa Bay Rowdies,0.0,1.0,None,...,2025-07-21T01:01:22.623644,20,Regular Season,Trinity Health Stadium,Cristian Campo Hernández,Brendan Burke,Dominic Casciato,1.1.0,2,2
1,3985850,2025-10-23,02:00:00.000,USA - USL Championship,2025,Sacramento Republic,Charleston Battery,1.0,0.0,None,...,2025-10-24T16:10:33.000000,30,Regular Season,Heart Health Park,Cristian Campo Hernández,Neill Collins,Ben Pirmann,1.1.0,2,2
2,3985706,2025-07-12,23:00:00.000,USA - USL Championship,2025,Indy Eleven,Rhode Island,1.0,0.0,None,...,2025-08-05T03:44:46.771615,19,Regular Season,"Michael A. Carroll Stadium (Indianapolis, Indi...",Mark Verso,Sean McAuley,Khano Smith,1.1.0,2,2
3,3985803,2025-09-12,22:00:00.000,USA - USL Championship,2025,Lexington SC,Orange County SC,1.0,1.0,None,...,2025-09-13T21:00:05.691791,27,Regular Season,Lexington Stadium,Elijio Arreguin,Terence Boss,Danny Stone,1.1.0,2,2
4,3985550,2025-03-22,21:00:00.000,USA - USL Championship,2025,New Mexico United,El Paso Locomotive,1.0,0.0,None,...,NaN,3,Regular Season,Isotopes Park,Gerald Flores,Dennis Sanchez,Wílmer Cabrera Linares,1.1.0,2,2

In [4]:
df_matches['match_id'].nunique()

375

In [8]:
df_player_season = pd.read_parquet(sb_data_folder_path + "/USLChampionship_2025_player_season.parquet")

In [6]:
df_player_season.head()

,account_id,player_id,player_name,team_id,team_name,competition_id,competition_name,season_id,season_name,country_id,...,player_season_fhalf_lbp_to_space_10_90,player_season_f3_lbp_to_space_10_90,player_season_lbp_to_space_2_90,player_season_fhalf_lbp_to_space_2_90,player_season_f3_lbp_to_space_2_90,player_season_lbp_to_space_5_90,player_season_fhalf_lbp_to_space_5_90,player_season_f3_lbp_to_space_5_90,player_season_360_minutes,player_season_defensive_actions_90
0,6040,34034,Alexis Souahy,1462,San Antonio,89,USL Championship,315,2025,50,...,0.000000,0.0,2.994366,0.748592,0.068054,1.156914,0.272215,0.0,1322.48340,6.817418
1,6040,41432,Nico Diago Gordon,8350,Monterey Bay,89,USL Championship,315,2025,153,...,0.104995,0.0,3.359841,0.419980,0.000000,1.574925,0.314985,0.0,857.18335,15.144361
2,6040,90633,Harvey Neville,1467,Phoenix Rising,89,USL Championship,315,2025,109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,10.074627
3,6040,218054,Stephen Carroll,2341,Detroit City,89,USL Championship,315,2025,109,...,0.000000,0.0,3.273566,0.125906,0.000000,1.007251,0.000000,0.0,714.81670,8.328992
4,6040,141759,Joshua O'Brien,1427,Indy Eleven,89,USL Championship,315,2025,109,...,0.000000,0.0,0.929672,0.232418,0.232418,0.697254,0.000000,0.0,387.23330,16.087300

In [7]:
df_player_season.columns.tolist()

['account_id',
 'player_id',
 'player_name',
 'team_id',
 'team_name',
 'competition_id',
 'competition_name',
 'season_id',
 'season_name',
 'country_id',
 'birth_date',
 'player_female',
 'player_first_name',
 'player_last_name',
 'player_known_name',
 'player_weight',
 'player_height',
 'player_season_minutes',
 'player_season_np_xg_per_shot',
 'player_season_np_xg_90',
 'player_season_np_shots_90',
 'player_season_goals_90',
 'player_season_npga_90',
 'player_season_xa_90',
 'player_season_key_passes_90',
 'player_season_op_key_passes_90',
 'player_season_assists_90',
 'player_season_through_balls_90',
 'player_season_passes_into_box_90',
 'player_season_op_passes_into_box_90',
 'player_season_touches_inside_box_90',
 'player_season_op_passes_into_and_touches_inside_box_90',
 'player_season_tackles_90',
 'player_season_interceptions_90',
 'player_season_tackles_and_interceptions_90',
 'player_season_padj_tackles_90',
 'player_season_padj_interceptions_90',
 'player_season_padj_tackles_and_interceptions_90',
 'player_season_challenge_ratio',
 'player_season_dribbles_90',
 'player_season_fouls_90',
 'player_season_dribbled_past_90',
 'player_season_dispossessions_90',
 'player_season_long_ball_ratio',
 'player_season_long_balls_90',
 'player_season_blocks_per_shot',
 'player_season_clearance_90',
 'player_season_aerial_ratio',
 'player_season_aerial_wins_90',
 'player_season_op_passes_90',
 'player_season_forward_pass_proportion',
 'player_season_backward_pass_proportion',
 'player_season_sideways_pass_proportion',
 'player_season_op_f3_passes_90',
 'player_season_op_f3_forward_pass_proportion',
 'player_season_op_f3_backward_pass_proportion',
 'player_season_op_f3_sideways_pass_proportion',
 'player_season_shot_on_target_ratio',
 'player_season_passing_ratio',
 'player_season_conversion_ratio',
 'player_season_npg_90',
 'player_season_crosses_90',
 'player_season_crossing_ratio',
 'player_season_penalty_wins_90',
 'player_season_padj_clearances_90',
 'player_season_passes_inside_box_90',
 'player_season_xgchain_90',
 'player_season_op_xgchain_90',
 'player_season_xgbuildup_90',
 'player_season_op_xgbuildup_90',
 'player_season_op_xa_90',
 'player_season_op_assists_90',
 'player_season_xgchain',
 'player_season_op_xgchain',
 'player_season_xgbuildup',
 'player_season_op_xgbuildup',
 'player_season_xgchain_per_possession',
 'player_season_op_xgchain_per_possession',
 'player_season_xgbuildup_per_possession',
 'player_season_op_xgbuildup_per_possession',
 'primary_position',
 'secondary_position',
 'player_season_pressured_long_balls_90',
 'player_season_unpressured_long_balls_90',
 'player_season_aggressive_actions_90',
 'player_season_pressures_90',
 'player_season_turnovers_90',
 'player_season_pressure_regains_90',
 'player_season_box_cross_ratio',
 'player_season_sp_xa_90',
 'player_season_shot_touch_ratio',
 'player_season_deep_progressions_90',
 'player_season_fouls_won_90',
 'player_season_shots_faced_90',
 'player_season_goals_faced_90',
 'player_season_np_xg_faced_90',
 'player_season_np_psxg_faced_90',
 'player_season_save_ratio',
 'player_season_xs_ratio',
 'player_season_gsaa_90',
 'player_season_gsaa_ratio',
 'player_season_left_foot_ratio',
 'player_season_pressured_passing_ratio',
 'player_season_passes_pressed_ratio',
 'player_season_pass_length',
 'player_season_s_pass_length',
 'player_season_p_pass_length',
 'player_season_ps_pass_length',
 'player_season_ot_shots_faced_90',
 'player_season_npot_psxg_faced_90',
 'player_season_ot_shots_faced_ratio',
 'player_season_np_optimal_gk_dlength',
 'player_season_clcaa',
 'player_season_pass_into_pressure_ratio',
 'player_season_pass_into_danger_ratio',
 'player_season_da_aggressive_distance',
 'player_season_positive_outcome_score',
 'player_season_appearances',
 'player_season_average_minutes',
 'player_season_positive_outcome_90',
 'player_season_sp_assists_90',
 'player_season_sp_key_passes_90',
 'player_season_npxgxa_90',
 'player_season_over_under_performance_90',
 'player_season_shots_key_passes_90',
 'player_season_failed_dribbles_90',
 'player_season_total_dribbles_90',
 'player_season_dribble_ratio',
 'player_season_sp_passes_into_box_90',
 'player_season_penalty_conversion_ratio',
 'player_season_pass_length_ratio',
 'player_season_pressured_pass_length_ratio',
 'player_season_change_in_passing_ratio',
 'player_season_pressured_change_in_pass_length',
 'player_season_carries_90',
 'player_season_carry_ratio',
 'player_season_carry_length',
 'player_season_dribble_faced_ratio',
 'player_season_counterpressures_90',
 'player_season_yellow_cards_90',
 'player_season_second_yellow_cards_90',
 'player_season_red_cards_90',
 'player_season_errors_90',
 'player_season_padj_pressures_90',
 'player_season_defensive_action_regains_90',
 'player_season_counterpressure_regains_90',
 'player_season_starting_appearances',
 'player_season_average_x_pressure',
 'player_season_fhalf_pressures_90',
 'player_season_fhalf_counterpressures_90',
 'player_season_fhalf_pressures_ratio',
 'player_season_fhalf_counterpressures_ratio',
 'player_season_average_x_defensive_action',
 'player_season_average_x_pass',
 'player_season_most_recent_match',
 'player_season_90s_played',
 'player_season_obv_90',
 'player_season_obv_pass_90',
 'player_season_obv_shot_90',
 'player_season_obv_defensive_action_90',
 'player_season_obv_dribble_carry_90',
 'player_season_obv_gk_90',
 'player_season_deep_completions_90',
 'player_season_ball_recoveries_90',
 'player_season_np_psxg_90',
 'player_season_penalties_faced_90',
 'player_season_penalties_conceded_90',
 'player_season_fhalf_ball_recoveries_90',
 'player_season_average_space_received_in',
 'player_season_average_fhalf_space_received_in',
 'player_season_average_f3_space_received_in',
 'player_season_ball_receipts_in_space_10_ratio',
 'player_season_ball_receipts_in_space_2_ratio',
 'player_season_ball_receipts_in_space_5_ratio',
 'player_season_fhalf_ball_receipts_in_space_10_ratio',
 'player_season_fhalf_ball_receipts_in_space_2_ratio',
 'player_season_fhalf_ball_receipts_in_space_5_ratio',
 'player_season_f3_ball_receipts_in_space_10_ratio',
 'player_season_f3_ball_receipts_in_space_2_ratio',
 'player_season_f3_ball_receipts_in_space_5_ratio',
 'player_season_lbp_90',
 'player_season_lbp_completed_90',
 'player_season_lbp_ratio',
 'player_season_fhalf_lbp_completed_90',
 'player_season_fhalf_lbp_ratio',
 'player_season_f3_lbp_completed_90',
 'player_season_f3_lbp_ratio',
 'player_season_fhalf_lbp_90',
 'player_season_f3_lbp_90',
 'player_season_obv_lbp_90',
 'player_season_fhalf_obv_lbp_90',
 'player_season_f3_obv_lbp_90',
 'player_season_lbp_pass_ratio',
 'player_season_fhalf_lbp_pass_ratio',
 'player_season_f3_lbp_pass_ratio',
 'player_season_lbp_received_90',
 'player_season_fhalf_lbp_received_90',
 'player_season_f3_lbp_received_90',
 'player_season_average_lbp_to_space_distance',
 'player_season_fhalf_average_lbp_to_space_distance',
 'player_season_f3_average_lbp_to_space_distance',
 'player_season_lbp_to_space_10_received_90',
 'player_season_fhalf_lbp_to_space_10_received_90',
 'player_season_f3_lbp_to_space_10_received_90',
 'player_season_lbp_to_space_2_received_90',
 'player_season_fhalf_lbp_to_space_2_received_90',
 'player_season_f3_lbp_to_space_2_received_90',
 'player_season_lbp_to_space_5_received_90',
 'player_season_fhalf_lbp_to_space_5_received_90',
 'player_season_f3_lbp_to_space_5_received_90',
 'player_season_average_lbp_to_space_received_distance',
 'player_season_fhalf_average_lbp_to_space_received_distance',
 'player_season_f3_average_lbp_to_space_received_distance',
 'player_season_lbp_to_space_10_90',
 'player_season_fhalf_lbp_to_space_10_90',
 'player_season_f3_lbp_to_space_10_90',
 'player_season_lbp_to_space_2_90',
 'player_season_fhalf_lbp_to_space_2_90',
 'player_season_f3_lbp_to_space_2_90',
 'player_season_lbp_to_space_5_90',
 'player_season_fhalf_lbp_to_space_5_90',
 'player_season_f3_lbp_to_space_5_90',
 'player_season_360_minutes',
 'player_season_defensive_actions_90']

In [9]:
df_events = pd.read_parquet(
    sb_data_folder_path + "/USLChampionship_2025.parquet",
    engine="pyarrow",
)

In [10]:
df_events.head()

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,shot_shot_shot_assist,goalkeeper_lost_in_play,shot_shot_goal_assist,shot_follows_dribble,goalkeeper_success_in_play,player_off_permanent,goalkeeper_lost_out,shot_kick_off,goalkeeper_penalty_saved_to_post,pass_xclaim
0,None,NaN,NaN,None,None,None,None,None,NaN,None,...,None,None,None,None,None,None,None,None,None,NaN
1,None,NaN,NaN,None,None,None,None,None,NaN,None,...,None,None,None,None,None,None,None,None,None,NaN
2,None,NaN,NaN,None,None,None,None,None,NaN,None,...,None,None,None,None,None,None,None,None,None,NaN
3,None,NaN,NaN,None,None,None,None,None,NaN,None,...,None,None,None,None,None,None,None,None,None,NaN
4,None,NaN,NaN,None,None,None,None,None,NaN,None,...,None,None,None,None,None,None,None,None,None,NaN

In [12]:
df_events.shape

(1164924, 136)

In [11]:
df_events.columns.tolist()

['50_50',
 'bad_behaviour_card',
 'ball_receipt_outcome',
 'ball_recovery_recovery_failure',
 'block_deflection',
 'block_offensive',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_right_foot',
 'counterpress',
 'dribble_no_touch',
 'dribble_outcome',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_offensive',
 'foul_committed_type',
 'foul_won_advantage',
 'foul_won_defensive',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'injury_stoppage_in_chain',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'miscontrol_aerial_won',
 'obv_against_after',
 'obv_against_before',
 'obv_against_net',
 'obv_for_after',
 'obv_for_before',
 'obv_for_net',
 'obv_total_net',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_end_location',
 'pass_goal_assist',
 'pass_height',
 'pass_inswinging',
 'pass_length',
 'pass_no_touch',
 'pass_outcome',
 'pass_outswinging',
 'pass_pass_cluster_id',
 'pass_pass_cluster_label',
 'pass_pass_cluster_probability',
 'pass_pass_success_probability',
 'pass_recipient',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player',
 'player_id',
 'position',
 'possession',
 'possession_team',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_gk_positioning_xg_suppression',
 'shot_gk_save_difficulty_xg',
 'shot_gk_shot_stopping_xg_suppression',
 'shot_key_pass_id',
 'shot_one_on_one',
 'shot_outcome',
 'shot_shot_execution_xg',
 'shot_shot_execution_xg_uplift',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'tactics',
 'team',
 'team_id',
 'timestamp',
 'type',
 'under_pressure',
 'dribble_nutmeg',
 'dribble_overrun',
 'foul_committed_penalty',
 'foul_won_penalty',
 'ball_recovery_offensive',
 'pass_deflected',
 'shot_deflected',
 'goalkeeper_punched_out',
 'clearance_other',
 'goalkeeper_shot_saved_to_post',
 'pass_miscommunication',
 'shot_redirect',
 'shot_saved_to_post',
 'pass_straight',
 'shot_open_goal',
 'block_save_block',
 'goalkeeper_shot_saved_off_target',
 'shot_saved_off_target',
 'shot_shot_shot_assist',
 'goalkeeper_lost_in_play',
 'shot_shot_goal_assist',
 'shot_follows_dribble',
 'goalkeeper_success_in_play',
 'player_off_permanent',
 'goalkeeper_lost_out',
 'shot_kick_off',
 'goalkeeper_penalty_saved_to_post',
 'pass_xclaim']

In [13]:
df_events['match_id'].nunique()

371